name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^5.1.0
  flutter_social_button: ^1.1.4+1
  shared_preferences: ^2.3.1
  youtube_player_flutter: ^8.1.2  # Add the latest version here
  youtube_video_player: ^0.1.1
  video_player: ^2.9.1
  provider: ^6.0.0
  url_launcher: ^6.1.7
  flutter_localization: ^0.2.2
  image_picker: ^0.8.7+3
  page_transition: ^2.0.9
  lottie: ^2.0.9
  swipeable_button_view: ^0.0.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  fluttertoast:
  firebase_database: ^11.1.6
  random_string: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/deit/
    
